version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    labels:
      - dependencies
      - actions
      - Skip Changelog
    schedule:
      interval: weekly
      day: sunday
  - package-ecosystem: gomod
    directory: /
    labels:
      - dependencies
      - go
      - Skip Changelog
    schedule:
      interval: weekly
      day: sunday
  - package-ecosystem: gomod
    directory: /app/pkg
    labels:
      - dependencies
      - go
      - Skip Changelog
    schedule:
      interval: weekly
      day: sunday
  - package-ecosystem: gomod
    directory: /app/services/im_service
    labels:
      - dependencies
      - go
      - Skip Changelog
    schedule:
      interval: weekly
      day: sunday