# ci for the project building
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: ci

on:
  push:
    branches: [ "main" , "develop"]
    paths-ignore:
      - "changelog.md"
      - "readme.md"
  pull_request:
    branches: [ "main" , "develop" ]

jobs:

  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.21

      - name: pkg build
        working-directory: ./app/pkg
        run: go build -v ./...

      - name: im build
        working-directory: ./app/services/im_service
        run: go build -v ./...

      - name: im test
        working-directory: ./app/services/im_service
        run: go test -v ./...